
    <!-- PRODUCTOS -->
    <section class="parallax img-p-1">
    </section>
    <section class="content">
        <h1 class="content-title reveal fade-top">PRODUCTOS</h1>
        <div class="content-body-p">
            <div id="carouselProductsCaptions" class="carousel slide carousel-fade reveal fade-bottom" data-bs-ride="true">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselProductsCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Coberturas"></button>
                    <button type="button" data-bs-target="#carouselProductsCaptions" data-bs-slide-to="1" aria-label="Musicales"></button>
                    <button type="button" data-bs-target="#carouselProductsCaptions" data-bs-slide-to="2" aria-label="Difusion"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="3000">
                    <img src="../../resources/images/productos/coberturas.png" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Coberturas</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit</p>
                    </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="3000">
                    <img src="../../resources/images/productos/musicales.png" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Musicales</h5>
                        <p>Atque omnis perspiciatis, molestiae voluptates quod rem illo.</p>
                    </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="3000">
                    <img src="../../resources/images/productos/difusion.png" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Difusion</h5>
                        <p>quo vitae aperiam nostrum dolore fugiat ea delectus deleniti,mollitia ipsum!</p>
                    </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselProductsCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselProductsCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </section> 

    <!-- SERVICIOS -->
    <section class="parallax img-p-2">
        <div class="caption">
            <span class="border">SERVICIOS</span>
        </div>
    </section>
    
    <div class="container serv-content">
        <div class="accordion accordion-flush accordion-custom" id="accordionServices">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Alquiler
                    </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionServices">
                    <div class="accordion-body"> Lorem ipsum dolor sit amet, consectetur ALQUILER adipisicing elit. 
                        Reiciendis culpa quo asperiores blanditiis, tempora deleniti obcaecati officia corrupti est voluptatibus libero nisi voluptatem, 
                        facilis, ratione consequuntur eveniet. Fugiat, eum voluptatum.</div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                        Asistencia Técnica
                    </button>
                    </h2>
                    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionServices">
                    <div class="accordion-body">
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. ASISTENCIA TÉCNICA Aliquam fugiat ipsam 
                        libero quis officia quia neque ullam, consequatur nihil soluta et vel harum dolorem illum laborum impedit. 
                        Saepe, magni consequatur? </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                        Postproducción
                    </button>
                    </h2>
                    <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionServices">
                    <div class="accordion-body">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                        Magni nostrum eaque voluptatum, temporibus, POSTPRODUCCIÓN vero officiis, quasi suscipit nemo error explicabo fuga 
                        voluptate in perspiciatis consequuntur! Aspernatur exercitationem numquam earum quis.</div>
                    </div>
                </div>
            </div>
        </div>
    

        <!-- Creo que las franjas blancas tienen que ver con que el accordion está en un break entre los parallax -->    

    <section class="parallax img-p-2">
    </section>

    <!-- NUESTROS TRABAJOS -->
    <section class="content">
        <h1 class="content-title reveal fade-top">NUESTROS TRABAJOS</h1>
        
        <div class="content-body-p fade-bottom">
            <div id="carouselProductsCaptions" class="carousel slide reveal fade-bottom" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="3000">
                    <img src="../../resources/images/trabajos/trabajo1.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <p>Descripción breve de trabajo 1</p>
                    </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="3000">
                    <img src="../../resources/images/trabajos/trabajo2.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <p>Descripción breve de trabajo 2</p>
                    </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="3000">
                    <img src="../../resources/images/trabajos/trabajo3.png" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <p>Descripción breve de trabajo 3</p>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="parallax img-p-3">
    </section>