
<section class="trans">
    <button type="button" class="btn btn-outline-secondary">Scroll button</button>
</section>

<section class="section grey">
    <div class="section-header">
        <h3 class="section-title reveal fade-top">/ PRODUCTOS</h3>
        <h2 class="section-subtitle  reveal fade-bottom">Ladrillo tiene los mejores productos para vos, ahre.</h2>
    </div>
    <div class="section-content">
        <div class="item reveal fade-left">
            <i class="fa-solid fa-clapperboard"></i>
            <h4 class="item-t">COBERTURAS</h4>
            <p class="item-p muted">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deleniti, blanditiis.</p>
        </div>
        <div class="item reveal fade-left">
            <i class="fa-solid fa-bullhorn"></i>
            <h4 class="item-t" >DIFUSION</h4>
            <p  class="item-p muted">Qui voluptatibus ut sunt eius veritatis quod quia, aliquid, distinctio quaerat nihil dolor.</p>
        </div>
        <div class="item  reveal fade-left">
            <i class="fa-solid fa-music"></i>
            <h4 class="item-t">MUSICALES</h4>
            <p class="item-p muted">Quibusdam, unde molestiae nisi laborum voluptatibus debitis.</p>
        </div>
    </div>
    <div class="section-btn reveal fade-left">
        <a href="../products/products.php">
            <button type="button" class="btn btn-outline-secondary">Conocé más</button>
        </a>
    </div>

</section>

