<header class="welcome">
    <div class="img-welcome">
        <img src="../../resources/images/logos/Copia de Isologotipo Naranja y Blanco SVG.svg" alt="Ladrillo Logo 2" id="logo-welcome">
    </div>
    <div class="reel">
        <video id="videoPlayer" class="video-js vjs-big-play-centered" width="900">
            <source src="../../resources/video/reel01.mp4" type="video/mp4">
            <!--
            <source src="../../resources/videoreel01.weebm" type="video/webm">
            -->
            <p class="vjs-no-js">
                To view this video please enable JavaScript, and consider upgrading to a
                web browser that
                <a href="https://videojs.com/html5-video-support/" target="_blank">
                    supports HTML5 video
                </a>
            </p>
        </video>
    </div>
</header>