<nav>
        <a href="../home/index.html" aria-hidden="true">
            <img src="../../resources/images/logos/iso.svg" alt="Ladrillo logo" id="logo-nav">
        </a>
        <input type="checkbox" id="check">
        <label for="check" class="hamburger">
            <i class="fa-solid fa-bars"></i>
        </label>

        <ul>
            <label for="check" class="hamburger btn-ul">
                <i class="fa-solid fa-bars"></i>
            </label>
            <li><a href="#prod">Productos</a></li>
            <li><a href="#serv">Servicios</a></li>
            <li><a href="../aboutUs/aboutUs.php">Quiénes somos</a></li>
            <li><a href="#trab">Nuestros trabajos</a></li>
            <li class="contactUs"><a href="#contacto">Contacto</a></li>
            <li class="brands-menu">
                <a href="https://www.facebook.com/ladrillouy">
                    <i class="fa-brands fa-square-facebook"></i>
                </a>
                <a href="https://www.instagram.com/ladrillo.coop/">
                    <i class="fa-brands fa-instagram"></i>
                </a>
                <a href="https://www.youtube.com/">
                    <i class="fa-brands fa-youtube"></i>
                </a>
            </li>
            
        </ul>
</nav>