
<!-- HEADER -->
<section class="parallax img-p-2">
    <div class="caption-left">
        <ul>
            <li id="first"><a href="../home/index.php">HOME</a></li>
            <span>/</span>
            <li>QUIENES SOMOS</li>
        </ul>
        <h1>QUIENES SOMOS</h1>
    </div>
</section>

<!-- CONTENT -->

<section class="section grey">
    <div class="section-header">
        <h3 class="section-title">/HOME/PRODUCTOS/COBERTURAS</h3>
        <h2 class="section-subtitle">COBERTURAS</h2>
    </div>
    <div class="section-content">
        <div class="section-products reveal-horizontal fade-right"> 
            <div class="section-products-img">
                <img src="../../resources/images/productos/coberturas.png" class="item-img"></img>
            </div>
            <div class="section-products-text muted">
                <div class="section-products-text-item">
                    <h3>COBERTURA COMPLETA</h3>
                    <p>Registro total de un evento o espectáculo.</p>
                </div>
                <div class="section-products-text-item">
                    <h3>SPOT DE EVENTO</h3>
                    <p>Registro parcial para resumen de un evento.</p>
                </div>
            </div>
        </div>
    </div>
</section>