<!-- HEADER -->
<section class="headers">
    <div class="caption-left">

    </div>
</section>

<!-- PRODUCTOS -->
<section class="parallax img-pr-1">
    <div class="caption-left">
        <!--
       <h3>home / productos</h3>
        -->
        <ul>
            <li id="first">home </li>
            <span>/</span>
            <li>productos </li>
        </ul>
        <h1>PRODUCTOS</h1>
    </div>
</section>